### ISSUE TITLE
Phase 1 - Name of Our Device

### ISSUE THREAD

**Issue by alsatiax** [deco3500-2017/3-Amigos#1]
What will we name our education based community pinboard? At the moment the name is AllTeach however we want a name to greater reflect the pinboard nature of the software.

- [x] Come up with 5 viable names for our prototype
- [x]  Decide on the best name

**Comment by abhume** [comment]
TeachPin, PinTeach, TeachUs, AllTeach, ShareTeach, PinShare, EduPin, PinEdu

**Comment by alsatiax** [comment]
EduBoard, EduPin, Pinform, Pinstruct

**Comment by Hachiko97** [comment]
Name suggestions:

1. Node
2. Erudition

**Comment by abhume** [comment]
I have been writing Eduboard in the proposal. Happy to change it, but it's my favourite so far.

**Comment by Hachiko97** [comment]
The best name decided by the group is EduBoard
