### ISSUE TITLE
Phase 2 - Wireframe

### ISSUE THREAD

**Issue by alsatiax** [deco3500-2017/3-Amigos#11]
- [x] Plan wireframe on paper (All)

- [x] Site map on paper and digital version in draw.io (Abby)

- [x] Logo - will inform colour scheme and typography (Gabby)

- [x] Paper prototype (Alison)

**Comment by alsatiax** [comment]
Here are the links to the paper wireframes:
![img_20170905_132249](https://user-images.githubusercontent.com/20625557/30044443-6fb88366-9240-11e7-929f-0e8f1a64707a.jpg)
![img_20170905_132305](https://user-images.githubusercontent.com/20625557/30044442-6fb876dc-9240-11e7-819c-b0456f73f215.jpg)
![img_20170905_132331](https://user-images.githubusercontent.com/20625557/30044444-6fb9267c-9240-11e7-8014-e28a9c4c2bef.jpg)

**Comment by alsatiax** [comment]
Paper prototype is done, I added the images to a new folder in the Google drive. Let me know if you'd like me to change anything.

**Comment by abhume** [comment]
![image](https://user-images.githubusercontent.com/30425399/31105439-85e56bd4-a827-11e7-92da-a5f6253f837d.png)

From the paper prototyping, a basic sitemap was developed, which further fleshes out these pages and how they interact with each other as well as differentiate from each other.

**Comment by abhume** [comment]
A description of the functionality and appearance of each page is also detailed:

Login Page
The login page will appear the same for both teachers and parents, however dependent on the user type, the user will be directed to a main page applicable to either teachers or parents. 
Main Page
The main page is the primary dashboard. This is where the uploaded content is located. 
Upload File
The upload file link is applicable only for teachers. This is where PDF documents can be uploaded to the dashboard with a comment. 
Share Link
The share link function is applicable only for teachers. This is where web addresses to can be uploaded to the dashboard with a comment. 
Settings
The settings page will appear the same for both teachers and parents. There are two functions in this page including viewer settings and account settings. Viewer settings allows users to alter the visual appearance of their dashboard by changing font type and size and adding a theme. Alternatively, account settings allows users to alter personal details like name, username, password and email as well as changing notification settings.  
External Document Viewer
The external document viewer allows users to expand uploaded content on the main dashboard. Users can then more thoroughly read, download and print content as well as view document details.
