### ISSUE TITLE
Phase 3 - User Test with Paper Prototype

### ISSUE THREAD

**Issue by alsatiax** [deco3500-2017/3-Amigos#13]
- [x] Create pro forma test plan for paper prototype 

- [x] Create Google Forms survey

- [x] Run paper prototype tests with 3 parents

- [x] Run paper prototype tests with 3 teachers

**Comment by alsatiax** [comment]
Pro forma test plans for the paper prototype user tests have been completed. The pro forma test plans are on Google Drive. This link can be found here: [https://drive.google.com/file/d/0B9AgKqlP8fNOTmVfNklfVDExTm8/view?usp=sharing](url)

**Comment by alsatiax** [comment]
Both parent and teacher user test surveys have been completed.
Link to teacher paper prototype user test survey [https://goo.gl/forms/Jw9kyU91ODuvAlPL2](url)
Link to parent paper prototype user test survey [https://goo.gl/forms/dtkS3AtW0nyWCixM2](url)

**Comment by alsatiax** [comment]
A link to the user testing tasks can be found on the Google Drive here: 
[https://docs.google.com/document/d/1bEDNKi3jbk2CuOWCg0L6O5HUYADF7YJyyL3Tu3nlbWw/edit?usp=sharing](url)

**Comment by alsatiax** [comment]
User test results for the paper prototypes have been collated and proforma test plans within design prototype documentation has been updated. A link to the project documentation can be found:
[https://drive.google.com/open?id=15zaVO5vPZc5dRXA6WV7eq6QH5XvUc4epOxM34Cpy9n8](url)
This document has also been uploaded to GitHub files.

**Comment by abhume** [comment]
We discussed in the stand-up that results suggested it is really important to advertise this concept to teachers as this still seem to be quite skeptical.
