### ISSUE TITLE
Phase 3 - Electronic Prototype

### ISSUE THREAD

**Issue by abhume** [deco3500-2017/3-Amigos#15]
Following analysis of results from the paper prototype user testing, changes and updates need to be made in order to design and develop the electronic prototype on Adobe XD. 

- [x]  Compile results (Alison)

- [x] Decide on changes and updates (All)

- [x] Generate visual design elements like colour scheme, typography and visual layout (Abby)

- [x] Create prototype images in illustrator (Alison)

- [x] Begin creating electronic prototype on Mockplus (Alison) 

- [x] Create electronic prototype user test plan (Alison)

- [x] Run electronic prototype user tests

**Comment by alsatiax** [comment]
The image files of the electronic prototype and prototype made in Mockplus have been uploaded. Prototype can only be accessed through Mockplus for user tests.

**Comment by alsatiax** [comment]
User test plan and run sheets have been created and are on the drive. A link to these can be found below:
[https://docs.google.com/document/d/1Z903T9RCWb08b-EEGlutGxaC84eQc-WB6SVCCBbENiI/edit?usp=sharing](url) for test plan
[https://docs.google.com/document/d/1j8w7lxXftO7d5uVvL7GufcMjF5wA66LtCxR3dGGZxgo/edit?usp=sharing](url) for run sheet

**Comment by alsatiax** [comment]
Electronic prototype has been reopened to update numerous features and release an updated electronic prototype

**Comment by alsatiax** [comment]
Electronic prototype can be accessed online at [http://run.mockplus.com/OzdSvo2FhZqEVzn5/index.html](url)

**Comment by alsatiax** [comment]
Link to electronic prototype 2 survey [https://goo.gl/forms/1qovqFwZD3n8v4oD2](url)

**Comment by alsatiax** [comment]
Electronic prototype exported HTML file has been uploaded to GitHub with link to online version of the electronic prototype.
