### ISSUE TITLE
Phase 1 - Team and Responsibilities 

### ISSUE THREAD

**Issue by abhume** [deco3500-2017/3-Amigos#4]
Description of each team member and their responsibilities. As well as this, describe how the team will work together.

- [x] List team members and course code

- [x] List the team manager

- [x] List who is responsible for logistics (equipment, meetings etc.)

- [x] List key roles (developer, designer, content manager, presenter)

- [x] Describe how decisions will be made

- [x] Describe how the team will handle poor performance and resolve conflicts

**Comment by alsatiax** [comment]
Have completed the paragraphs of the proposal on Team and Responsibilities. @Hachiko97 all that is left is for you to list your details.
